### ISSUE TITLE
master doesn't compile against nginx-1.14.0

### ISSUE THREAD

**Issue by hadret** [weibocom/nginx-upsync-module#214]
`upsync_module` fails to compile against latest nginx release (1.14.0).

Error message during the compilation is the following:

```
[...]
/build/nginx-1.14.0/debian/modules/http-upsync/src/ngx_http_upsync_module.c: In function 'ngx_http_upsync_init_server':
/build/nginx-1.14.0/debian/modules/http-upsync/src/ngx_http_upsync_module.c:3099:64: error: expected ',' or ';' before 'cur'
     ngx_int_t                                n = 0, random = 0 cur = 0;
                                                                ^
In file included from src/core/ngx_core.h:12:0,
                 from /build/nginx-1.14.0/debian/modules/http-upsync/src/ngx_http_upsync_module.c:7:
src/core/ngx_config.h:57:34: error: called object 'random' is not a function or function pointer
 #define ngx_random               random
                                  ^
/build/nginx-1.14.0/debian/modules/http-upsync/src/ngx_http_upsync_module.c:3169:18: note: in expansion of macro 'ngx_random'
         random = ngx_random() % n;
                  ^
/build/nginx-1.14.0/debian/modules/http-upsync/src/ngx_http_upsync_module.c:3099:53: note: declared here
     ngx_int_t                                n = 0, random = 0 cur = 0;
                                                     ^
/build/nginx-1.14.0/debian/modules/http-upsync/src/ngx_http_upsync_module.c:3175:17: error: 'cur' undeclared (first use in this function)
             if (cur != random) {
                 ^
/build/nginx-1.14.0/debian/modules/http-upsync/src/ngx_http_upsync_module.c:3175:17: note: each undeclared identifier is reported only once for each function it appears in
objs/Makefile:1545: recipe for target 'objs/addon/src/ngx_http_upsync_module.o' failed
[...]
```

This problem was introduced with https://github.com/weibocom/nginx-upsync-module/commit/49163854a4dc1b7956aa43dc0630a7d2b8a8ad37 commit. Earlier versions from master are compiling fine.

**Comment by hadret** [comment]
Fixed in https://github.com/weibocom/nginx-upsync-module/commit/d050059, thank you!
